# Generated by Django 3.2.7 on 2021-09-02 14:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0004_auto_20210902_1042"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("date", models.DateTimeField()),
                (
                    "result",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "nWinnersByRange",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "prizesInfoByRange",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("earnedValue", models.FloatField()),
                ("nextDrawEstimatedPrize", models.FloatField()),
                ("nextDrawAccumulatedPrize", models.FloatField()),
                ("drawHasAccumulated", models.BooleanField()),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottery.lottery",
                    ),
                ),
            ],
        ),
    ]
