# Generated by Django 3.2.7 on 2021-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0005_draw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draw",
            name="date",
            field=models.DateField(),
        ),
    ]
