# Generated by Django 3.2.7 on 2021-11-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20211023_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
