# Generated by Django 3.2.7 on 2021-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_game_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='numberOfGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='numberOfGamesets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameset',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameset',
            name='numberOfGames',
            field=models.IntegerField(default=0),
        ),
    ]
