# Generated by Django 3.2.7 on 2021-11-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_auto_20211108_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='gameLength',
            field=models.IntegerField(default=0),
        ),
    ]
