# Generated by Django 3.2.7 on 2021-11-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0013_gameset_gamelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='subtract',
            field=models.IntegerField(default=0),
        ),
    ]
