# Generated by Django 3.2.7 on 2021-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0014_game_subtract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='subtract',
        ),
        migrations.AddField(
            model_name='game',
            name='binaryMask',
            field=models.BinaryField(null=True),
        ),
    ]
