# Generated by Django 3.2.7 on 2021-11-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_auto_20211109_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='binaryMask',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
