# Generated by Django 3.2.7 on 2021-11-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0016_alter_game_binarymask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='binaryMask',
        ),
        migrations.AddField(
            model_name='game',
            name='gameCode',
            field=models.BigIntegerField(default=0),
        ),
    ]
