# Generated by Django 3.2.7 on 2021-11-10 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0017_auto_20211109_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='nWinnersByRange',
        ),
        migrations.AddField(
            model_name='draw',
            name='extraResultField',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='metadata',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='draw',
            name='prizesInfoByRange',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
    ]
