# Generated by Django 3.2.7 on 2021-11-10 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0018_auto_20211110_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='prizesInfoByRange',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None),
        ),
    ]
