# Generated by Django 3.2.7 on 2021-11-11 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0019_alter_draw_prizesinfobyrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='metadata',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=None),
        ),
    ]
