# Generated by Django 3.2.7 on 2021-11-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0020_alter_draw_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='lottery.lottery', verbose_name='Lottery type'),
        ),
    ]
