# Generated by Django 3.2.7 on 2021-11-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0021_alter_draw_lottery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ['number'], 'verbose_name': 'Draw', 'verbose_name_plural': 'Draws'},
        ),
        migrations.AddField(
            model_name='draw',
            name='maxPrize',
            field=models.FloatField(null=True, verbose_name='Max prize'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='date',
            field=models.DateField(verbose_name='Draw date'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='drawHasAccumulated',
            field=models.BooleanField(verbose_name='Draw had winners?'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='lottery.lottery', verbose_name='Lottery'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Draw number'),
        ),
    ]
