# Generated by Django 3.2.7 on 2021-11-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0022_auto_20211111_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draw',
            old_name='drawHasAccumulated',
            new_name='hasAccumulated',
        ),
    ]
