# Generated by Django 3.2.7 on 2022-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0023_rename_drawhasaccumulated_draw_hasaccumulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_odd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='max_gap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='max_seq',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='min_seq',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='n_primes',
            field=models.IntegerField(default=-1),
        ),
    ]
