# Generated by Django 3.2.7 on 2022-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0024_auto_20220120_1702'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['sum', 'gameCode'], name='games_sum_d23851_idx'),
        ),
    ]
