# Generated by Django 3.2.7 on 2022-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0025_game_games_sum_d23851_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_sum_d23851_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['arrayNumbers'], name='games_arrayNu_b42df6_idx'),
        ),
    ]
