# Generated by Django 3.2.7 on 2022-02-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0026_auto_20220123_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='is_odd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draw',
            name='max_gap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='draw',
            name='max_seq',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='draw',
            name='min_seq',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='draw',
            name='n_primes',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='draw',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
