# Generated by Django 3.2.7 on 2022-02-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0027_auto_20220205_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='is_odd',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_odd',
        ),
        migrations.AddField(
            model_name='draw',
            name='parity',
            field=models.CharField(choices=[('odd', 'Ímpar'), ('even', 'Par'), ('neutral', 'Neutro')], default='neutral', max_length=128),
        ),
        migrations.AddField(
            model_name='game',
            name='parity',
            field=models.CharField(choices=[('odd', 'Ímpar'), ('even', 'Par'), ('neutral', 'Neutro')], default='neutral', max_length=128),
        ),
    ]
