# Generated by Django 3.2.7 on 2022-02-12 13:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0028_auto_20220205_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='lottery.lottery', verbose_name='N-uplas Combinations')),
            ],
        ),
    ]
