# Generated by Django 3.2.7 on 2022-02-12 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0030_auto_20220212_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='combs_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
