# Generated by Django 3.2.7 on 2022-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0032_combinations_combination_n_8f8147_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='last_draw_number',
            field=models.IntegerField(default=0),
        ),
    ]
