# Generated by Django 3.2.7 on 2022-02-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0034_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Collections Result', 'verbose_name_plural': 'Collections Results'},
        ),
        migrations.AlterModelTable(
            name='result',
            table='results',
        ),
    ]
